fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "carlos.lucero@epn.edu.ec"
    sender_name: "Carlos Lucero"
  registration:
    form:
      type: App\Form\RegistrationType

    confirmation:
      enabled: true