vich_uploader:
    db_driver: orm

    mappings:
        objetos_image:
            uri_prefix: /images/objetos
            upload_destination: '%kernel.project_dir%/public/images/objetos'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true